/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("PackageTest.java-conventions")
}

dependencies {
    implementation("mysql:mysql-connector-java:8.0.22")
}

group = "Internship"
description = "UsingMYSQL"
